version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    # Adding network configuration to make it discoverable by external Prometheus
    networks:
      - app-network
      - default

  grafana:
    image: grafana/grafana
    ports:
      - "8102:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - app-network
      - default

volumes:
  grafana-storage:

# Create a named network that can be joined by the external Prometheus
networks:
  app-network:
    name: app-monitoring
    driver: bridge
