version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/config.yml'
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "8101:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "8102:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:

